
---
title: "CRS-2024"
author: "Nano Castro"
date: "2024-01-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r datos}
library(tidyverse)
library(lubridate)
setwd("~/Documentos/GitHub/CO2-soil-respiration-chamber/measurements/2024")
rm(list = ls())
crs_crudos<-read.csv("2024-1-25_Crece21.csv")
crs_crudos<-crs_crudos[1:9]
colnames(crs_crudos)<-c("Time","ID","Temp","Presion","CO2","HR","T2","field6","Altura")
crs_crudos$Time<-ymd_hms(crs_crudos$Time, tz="America/Buenos_Aires")
# str(crs_crudos)

```

```{r simple_plot}
library(hrbrthemes)
# plot
crs_crudos%>% 
  ggplot( aes(x=Time, y=CO2)) +
    geom_line(color="#69b3a2") +
    #annotate(geom="text", x=as.Date("2017-01-01"), y=20089, 
    #         label="Bitcoin price reached 20k $\nat the end of 2017") +
    #annotate(geom="point", x=as.Date("2017-12-17"), y=20089, size=10, shape=21, fill="transparent") +
    geom_hline(yintercept=5000, color="orange", linewidth=.5) +
    scale_x_datetime(breaks="2 hour",date_labels="%H")+
    # geom_smooth()+
    theme_ipsum()

# Tiempo en el que inicia el test (cuando cerramos la tapa)
start_time=as.POSIXct("2024-01-25 13:10:00")
# Tiempo en el que llega al máximo (se elige la primera vez que llega al valor máximo de CO2)
max<-subset(crs_crudos, crs_crudos$CO2==max(crs_crudos$CO2, na.rm=TRUE))
asympt_time<-min(max$Time)
crs_crudos_resp<-subset(crs_crudos, Time>=start_time & Time<=asympt_time)
# test_time<-hours(6)
# short_time<-start_time + test_time
# crs_crudos_resp<-subset(crs_crudos, Time>=start_time & Time<=short_time)
# crs_crudos_resp_tot<-subset(crs_crudos, Time>=asympt_time)


# crs_crudos_resp%>% 
#   ggplot( aes(x=Time, y=CO2)) +
#     geom_line(color="#69b3a2") +
#     #annotate(geom="text", x=as.Date("2017-01-01"), y=20089, 
#     #         label="Bitcoin price reached 20k $\nat the end of 2017") +
#     #annotate(geom="point", x=as.Date("2017-12-17"), y=20089, size=10, shape=21, fill="transparent") +
# #    geom_hline(yintercept=5000, color="orange", linewidth=.5) +
#     scale_x_datetime(breaks="2 hour",date_labels="%H")+
#     #geom_smooth()+
#     theme_ipsum()

```

[Regresion no lineal](https://tuos-bio-data-skills.github.io/intro-stats-book/non-linear-regression-in-R.html)
[Modelos](https://www.statforbiology.com/nonlinearregression/usefulequations#asymptotic_regression_model)

```{r model}

library(drc)
library(dplyr)
crs_crudos_resp<-mutate(crs_crudos_resp,elapsed=as.numeric(Time - first(Time), units = "mins"))
fm1 <- nls(CO2 ~ SSasymp(elapsed, Asym,resp0,lrc),data=crs_crudos_resp)
summary(fm1)
crs_model<-data.frame(predict(fm1,crs_crudos_resp$elapsed))
crs_model<-mutate(crs_model,elapsed=crs_crudos_resp$elapsed)
colnames(crs_model)=c("CO2","elapsed")
crs_crudos_resp<-mutate(crs_crudos_resp,model=crs_model$CO2)

ggplot(crs_crudos_resp, aes(x = elapsed, y = CO2)) + 
  geom_point(color="#69b3a2") + geom_line(data = crs_model,color="red") +
  xlab("Elapsed time (min)") + ylab("CO2 (ppm)") + 
  theme_bw(base_size = 10)

crs_diff<-mutate(crs_crudos_resp,differencia=CO2-model)


ggplot(crs_diff, aes(x = elapsed, y = differencia)) + 
  geom_line(color="red") +
  xlab("Elapsed time (min)") + ylab("Diferencia CO2 (ppm)") + 
  theme_bw(base_size = 10)

```

```{r model_tot}

crs_crudos_resp_tot<-mutate(crs_crudos_resp_tot,elapsed=as.numeric(Time - first(Time), units = "mins"))
fm1 <- nls(CO2 ~ SSasymp(elapsed, Asym,resp0,lrc),data=crs_crudos_resp_tot)
summary(fm1)
crs_model<-data.frame(predict(fm1,crs_crudos_resp_tot$elapsed))
crs_model<-mutate(crs_model,elapsed=crs_crudos_resp_tot$elapsed)
colnames(crs_model)=c("CO2","elapsed")
crs_crudos_resp_tot<-mutate(crs_crudos_resp_tot,model=crs_model$CO2)

ggplot(crs_crudos_resp_tot, aes(x = elapsed, y = CO2)) + 
  geom_point(color="#69b3a2") + geom_line(data = crs_model,color="red") +
  xlab("Elapsed time (min)") + ylab("CO2 (ppm)") + 
  theme_bw(base_size = 10)


```

```{r model_xts}
library(xts)
library(dygraphs)
rm(crs_crudos_xts)
crs_crudos_xts<-as.xts(crs_crudos[,c(1,3,5)])

dygraph(crs_crudos_xts) %>%
  dySeries("CO2", label = "CO2 (ppm)") %>%
  dySeries("Temp", label="Temp (°C)",axis = 'y2')%>% 
 dyRangeSelector()


```
